# fly.toml app configuration file generated for produtos-testados-wandering-sea-5428 on 2024-12-16T16:37:20-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'produtos-testados-wandering-sea-5428'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
